### ISSUE TITLE
Porady

### ISSUE THREAD

**Issue by wokalove** [FilFib/NBAjesrseyShop#6]
Siemka!

Cieszę się, że tak dużo pracy wykonujecie i bardzo doceniam, że piszecie i robicie wszystko na bieżąco ;)

##Praca z gitem

### Commity
Ogólnie wiadomości mi się podobają, bo mówią o tym faktycznie co się zadziało w kodzie, niemniej znalazłam jednego, który mi się nie podoba :P ["Update"](https://github.com/FilFib/NBAjesrseyShop/commit/789403a2659afa9c053ec76463e989f6f443815c) nic nie mówi i jak się coś wysypie w tym commicie to możecie nawet nie skumać, że to chodzi o konkretną funkcjonalność, która się sypie.

### Branche

`orders2` - niewiadomo do końca o co chodzi - czy to jest jakaś ulepszona wersja, która powstała na bazie orders, czy jakiś zupełnie inny koncept. Staramy się albo to lepiej opisywać, a w przypadku kiedy gałąź nie jest jakaś już nam potrzebna, bo inna już zawiera jej kod to może warto ją usunąć po prostu.
Super, że działaliście sobie na różnych branchach i mergowaliście do developa, to działanie jest dobre.

## Foldery

`NBAjesrseyShop` - u Was nazywa się tak główny folder i apka, więc tak trochę nie bardzo wiadomo o co chodzi. Może lepszym by było `NBAjesrsey` na główny folder, a potem `NBAjesrseyShop`  albo `shop` jako apka

## Kod 
- [tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/NBAjesrseyShop/urls.py#L22) jest jakaś nieścisłość, bo oba includy są podpięte pod ten sam url i w zasadzie `accounts.urls` będzie pomijane albo co gorsza będzie jakiś konflikt w przyszlości 
- duży plus za widoki class based,
- [Tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/accounts/forms.py#L22C1-L23C1) niepotrzebne te nawiasy wokół `True` plus czy gdzieś używacie tego `is_active`? Nie wyszukuje mi, żeby było uzywane gdzieś w waszym repo, ale możliwe, że tutaj wyszukiwarka słabo działa.
- [Tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/accounts/models.py#L27) się ciutkę powtarzacie, więc może warto byłoby jakoś uprościć. I ogólnie widzę, że albo macię załogę albo zwykłego użytkownika. Czyli wnioskuję, że `staff` jest też superuserem. Czy nie lepiej ustawiać w takim razie jedno z któryś tych pól? Albo dotyczące staff albo superuser?
- [Nazwy routów z userem](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/accounts/urls.py#L6) - raczej daje się po prostu login, a nie `login_user`. Raczej wiadomo, że chodzi o to, że użytkownik będzie się logował, a jeśli będzie się logować szympans to teraz pytanie z deczka filozofiiczne - czy można go nazwać userem :D Więc tak czy siak bym nie personalizowała tego chyba

-Czemu  [tutaj ](https://github.com/FilFib/NBAjesrseyShop/blob/develop/NBAjesrseyShop/cart/admin.py) jest admin jak z niego nie korzystacie?
- Plus za skorzystanie z [iteratora!](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/cart.py#L13)
- przechowywanie [stringa ](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/cart.py#L33C42-L33C42) dla cen to raczej nie jest najlepszy pomysł, lepszy będzie już jakiś decimal
- [tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/cart.py#L17) idziecie po kluczach i wartościach, może lepiejcoś w stylu `    for product_variant_id, item in cart.items():`, bo tutaj macie dość to skomplikowanie napisane
- [klik](https://github.com/FilFib/NBAjesrseyShop/blob/develop/NBAjesrseyShop/cart/context_processors.py) - nie jestem przekonana, czy to potrzebne
- [globali](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/forms.py#L5) raczej unikamy. Wiem, że to wygodne, ale to chociaż wrzuccie to do jakiejś klasy z singletonem, jakkolwiek to zabezpieczcie. Bo każdy dev moze wam teraz w tej zmiennej namieszać i potem się głupotki wyświetlą
- [tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/cart.py#L34) nie wiem do końca o co chodzi, ale sprawdźcie, czy też przypadkiem tutaj ktoś nie może wrzucić np -2, bo jeśli wrzuci to powinien być wyjątek obsłużony.
- nie jestem do konca przekonana jednak czy `cart` na pewno musi być jako osobna apka, no bo zobaczcie - [tutaj models](https://github.com/FilFib/NBAjesrseyShop/blob/develop/NBAjesrseyShop/cart/models.py) macie pusty, bo korzystacie pewnie z jakichś modeli z innych apek - ogólnie ciężko się doszukać np modelu do bazy danych Cart, bo on teoretycznie powinien być w `models.py` tak patrząc po intuicji.  Może warto sklep polączyć z koszykiem?
- [tutaj nazwa](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/urls.py#L10)  `cart_remove` - czyli usuwam cały koszyk? :D lepiej by było coś w stylu `cart_remove_product`

## Templatki i CSS

- super, że macie jakiegoś template bazowego, ale dobrze by było pomyśleć, czy coś jeszcze w niektórych sekcjach się nie powiela i stworzyć bazowe dla grupy templatek,
- style mają być w pliku css, a nie jak [tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/shop/templates/home.html#L37) w HTML
- gdzie jest w ogóle jakiś folder na cssy? Jakiś w stylu `styles `albo `static `powinien być
Sprobujcie coś podziałać. Fajnie, że działa, ale fajnie też jak użytkownika oko cieszyć będzie ;)

Ogólnie podoba mi się, że okrzsytacie np z list comprehensions, że są właśnie widoki klasowe z metą i ogólnie widać, że staracie się nie powtarzać. 

Dużo fajnej pracy wykonaliście i keep going, bo ogólnie jest dobrze <3 
Gratuluję! 🥇

**Comment by FilFib** [comment]
### Praca z Gitem

**Commity**
Ogólnie wiadomości mi się podobają, bo mówią o tym faktycznie co się zadziało w kodzie, niemniej znalazłam jednego, który mi się nie podoba :P ["Update"](https://github.com/FilFib/NBAjesrseyShop/commit/789403a2659afa9c053ec76463e989f6f443815c) nic nie mówi i jak się coś wysypie w tym commicie to możecie nawet nie skumać, że to chodzi o konkretną funkcjonalność, która się sypie.

> Dzięki za uwagę. Poprawiliśmy opis i czytelność commitów ;)

**Branche**
orders2 - niewiadomo do końca o co chodzi - czy to jest jakaś ulepszona wersja, która powstała na bazie orders, czy jakiś zupełnie inny koncept. Staramy się albo to lepiej opisywać, a w przypadku kiedy gałąź nie jest jakaś już nam potrzebna, bo inna już zawiera jej kod to może warto ją usunąć po prostu.
Super, że działaliście sobie na różnych branchach i mergowaliście do developa, to działanie jest dobre.

> dzięki, usunęliśmy nie potrzebne branche

### Foldery
NBAjesrseyShop - u Was nazywa się tak główny folder i apka, więc tak trochę nie bardzo wiadomo o co chodzi. Może lepszym by było NBAjesrsey na główny folder, a potem NBAjesrseyShop albo shop jako apka

> Potraktujemy to już jako uwagę na przyszłość przy tworzeniu następnego projektu, gdyż na tym etapie zmiana nazw jest już dla nas zbyt ryzykowna pod względem poprawnego działania aplikacji ;) 

### Kod
[tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/NBAjesrseyShop/urls.py#L22) jest jakaś nieścisłość, bo oba includy są podpięte pod ten sam url i w zasadzie accounts.urls będzie pomijane albo co gorsza będzie jakiś konflikt w przyszlości

> Jest to celowe zagranie gdyż chcieliśmy wykorzystać standardowe Djangowe funkcję zawartę 'django.contrib.auth.urls' jak logowanie czy wylogowanie, ostatecznie logowanie i wylogowanie nadpisaliśmy innymi klasami dziedzicząc po LoginView i LogoutView gdyż chcieliśmy żeby po zalogowaniu i wylogowaniu przenosiło nas na stronę startową, a nie tak jak jest zakodowane w tych standardowych funkcjach np. po zalogowaniu przenosi na url "/profile". W związku z czym na ten moment usuwamy path('accounts/', include('django.contrib.auth.urls')) z accounts.urls.py

duży plus za widoki class based,
[Tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/accounts/forms.py#L22C1-L23C1) niepotrzebne te nawiasy wokół True plus czy gdzieś używacie tego is_active? Nie wyszukuje mi, żeby było uzywane gdzieś w waszym repo, ale możliwe, że tutaj wyszukiwarka słabo działa.

> Musimy ustawić użytkowanika przy zapisywaniu jako aktywnego  - is_active = True -  gdyż inaczej nie działa logowanie ;) dziedziczymy ze standardowego modelu użytkownika z Django.

[Tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/accounts/models.py#L27) się ciutkę powtarzacie, więc może warto byłoby jakoś uprościć. I ogólnie widzę, że albo macię załogę albo zwykłego użytkownika. Czyli wnioskuję, że staff jest też superuserem. Czy nie lepiej ustawiać w takim razie jedno z któryś tych pól? Albo dotyczące staff albo superuser?

> W tym momencie rzeczywiście jest to niepotrzebne, lecz chcemy to zostawić z myślą o przyszłym rozwijaniu projektu tak by admin mógł nadawać wybranym użytkownikom uprawnienia dostępu (is staff) np. do dodawania produktów do sklepu czy obsługi zamówień.

[Nazwy routów z userem](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/accounts/urls.py#L6) - raczej daje się po prostu login, a nie login_user. Raczej wiadomo, że chodzi o to, że użytkownik będzie się logował, a jeśli będzie się logować szympans to teraz pytanie z deczka filozofiiczne - czy można go nazwać userem :D Więc tak czy siak bym nie personalizowała tego chyba

> zmienione na /login i /logout/ ;)

-Czemu [tutaj ](https://github.com/FilFib/NBAjesrseyShop/blob/develop/NBAjesrseyShop/cart/admin.py)jest admin jak z niego nie korzystacie?

> usunięto plik admin.py

Plus za skorzystanie z [iteratora!](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/cart.py#L13)

> Dzięki!

przechowywanie [stringa ](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/cart.py#L33C42-L33C42)dla cen to raczej nie jest najlepszy pomysł, lepszy będzie już jakiś decimal

> Ogólnie price w modelu jest decimalem, ale musielismy go przełożyć na coś innego bo wyskakiwał nam błąd "Object of type Decimal is not JSON serializable", stąd string, ale zmieniłem już teraz na float po Twojej uwadze więc powinno być ok.

[tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/cart.py#L17) idziecie po kluczach i wartościach, może lepiej coś w stylu     for product_variant_id, item in cart.items():, bo tutaj macie dość to skomplikowanie napisane

> jeśli starczy czasu pochylimy się jeszcze nad optymalizacja tego fragmentu, ale niezależnie od wyglądu działa prawidłowo ;D 

[klik](https://github.com/FilFib/NBAjesrseyShop/blob/develop/NBAjesrseyShop/cart/context_processors.py) - nie jestem przekonana, czy to potrzebne

> To jest nam potrzebne by podawać zawartość koszyka do każdej templatki, by każdym miejscu na naszej stronie obojętnie na jaki url wejdziesz do góry było widać ile masz przedmiotów w koszyku i jego wartość, umieściliśmy tą informacje w base.html ;) Koszyk przechowujemy w sesji. wpisaliśmy ten context_procesor to settings i fajnie to śmiga.

[globali](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/forms.py#L5) raczej unikamy. Wiem, że to wygodne, ale to chociaż wrzuccie to do jakiejś klasy z singletonem, jakkolwiek to zabezpieczcie. Bo każdy dev moze wam teraz w tej zmiennej namieszać i potem się głupotki wyświetlą

> zmienimy to tak by dostępna ilość produktu w przypadku stock_quantity > 10 wyświetlała tylko liczbę 10, a w innym przypadku wyświetlało do wyboru max stock_quantity.

[tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/cart.py#L34) nie wiem do końca o co chodzi, ale sprawdźcie, czy też przypadkiem tutaj ktoś nie może wrzucić np -2, bo jeśli wrzuci to powinien być wyjątek obsłużony.

> override_quantity jest używane przy update ilości w koszyku, jest to pole typu boolean ukryte dla użytkownika, przy dodawaniu produktu do koszyka ustawione na False, ale w przypadku metody update już na stronie koszyka jest ustawione na True i w tym przypadku, działa ten warunek właśnie, który zaznaczyłaś i nadpisuję nam dotychczasową ilość nową ilością podaną przez użytkownika. User nie może wybrać innej wartości niż określiliśmy w formularzu czyli max 1-10 lub 1-stock_qunatity jeśli stock_quantity<10.

nie jestem do konca przekonana jednak czy cart na pewno musi być jako osobna apka, no bo zobaczcie - [tutaj models](https://github.com/FilFib/NBAjesrseyShop/blob/develop/NBAjesrseyShop/cart/models.py) macie pusty, bo korzystacie pewnie z jakichś modeli z innych apek - ogólnie ciężko się doszukać np modelu do bazy danych Cart, bo on teoretycznie powinien być w models.py tak patrząc po intuicji. Może warto sklep polączyć z koszykiem?

> Cart przechowujemy tylko w sesji, nie wykorzystujemy do tego modelu i bardzo fajnie to działa póki co. Folder models usuniemy z tej aplikacji bo jest niepotrzebny. Tak naprawdę nie musieliśmy tworzyć nowej aplikacji i można to było wszystko zrobić w shopie i tylko inaczej ponazywać foldery "views.py", ale wydawało nam się, że tak będzie większy porządek ;) 

[tutaj nazwa](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/cart/urls.py#L10) cart_remove - czyli usuwam cały koszyk? :D lepiej by było coś w stylu cart_remove_product

> nazwa zmieniona na cart_remove_product ;)

### Templatki i CSS
super, że macie jakiegoś template bazowego, ale dobrze by było pomyśleć, czy coś jeszcze w niektórych sekcjach się nie powiela i stworzyć bazowe dla grupy templatek,

> na ten moment nie mamy jeszcze takich rzeczy, ale przy rozwoju projektu na pewno się to przyda ;)

style mają być w pliku css, a nie jak [tutaj](https://github.com/FilFib/NBAjesrseyShop/blob/061834b5997e30100715f4a2daae83145effbecf/NBAjesrseyShop/shop/templates/home.html#L37) w HTML

> przeniesiono do foldera style.css ;)

gdzie jest w ogóle jakiś folder na cssy? Jakiś w stylu styles albo static powinien być
Sprobujcie coś podziałać. Fajnie, że działa, ale fajnie też jak użytkownika oko cieszyć będzie ;)

> póki co w dużej mierze ozdabiamy html bootstrapem, ale dodalismy także folder z cssami ;)
